# Generated by Django 4.1.5 on 2023-01-16 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photography_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='photo_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 16, 10, 55, 21, 345272)),
        ),
    ]
