# Generated by Django 4.1.5 on 2023-01-16 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_photography_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%M/%d/'),
        ),
        migrations.AlterField(
            model_name='photography',
            name='photo_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 16, 11, 48, 28, 210309)),
        ),
    ]
